name: Build Base Docker Image

on:
  workflow_dispatch: # Allows manual triggering
  push:
    branches:
      - main # Or whichever branch you want to trigger builds from
    paths:
      - 'Dockerfile' # Only trigger on Dockerfile changes for pushes

jobs:
  build:
    # Grant GITHUB_TOKEN permissions to write packages
    permissions:
      contents: read # Needed for checkout
      packages: write # Needed to push to GHCR

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # Use GITHUB_TOKEN for GHCR within the same repo/org

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }} # Generates ghcr.io/owner/repo
          tags: |
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64 # Specify the target platform
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true # Enable pushing to the registry
